#execute all tests generated by build.bat
#Output files:
.\build\intel_avb.lib   # Static library
.\build\intel_avb.dll   # Dynamic library
.\build\test_intel.exe      # Simulated API test
.\build\test_realmode.exe   # Real IOCTL interface test
.\build\test_i226_priority.exe # I226 preference test
.\build\test_multi_adapter.exe # Multi-adapter test
.\build\test_tsn_support.exe # TSN IOCTL support test
.\build\demo_parallel_services.exe # Parallel services demonstration
.\build\test_filter_driver.exe # Filter driver test
